# Generated by Django 4.2.3 on 2023-07-27 10:52

from django.db import migrations

# create initial customer with id 101
def create_initial_customer(apps, schema_editor):
    Customer = apps.get_model('xnara', 'Customer')
    Customer.objects.create(customer_id=101)

class Migration(migrations.Migration):

    dependencies = [
        ('xnara', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_customer)
    ]
